function initGuildPic(){	
	//首页
	$("#mainguid_traff").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#1c5196');
	    	 },
	    mouseout:function(){
	    	    $(this).css('background-color','#1f5aa7');
	    	 }
	});
	$("#mainguid_road").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#007474');
	    	 },
	    mouseout:function(){
	    	   $(this).css('background-color','#008181');
	    	 }
	});
	$("#mainguid_transport").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#26a854');
	    	 },
	    mouseout:function(){
	    	    $(this).css('background-color','#2abb5d');
	    	 }
	});
	$("#mainguid_outgo").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#2680e5');
	    	 },
	    mouseout:function(){
	    	    $(this).css('background-color','#2a8eff');
	    	 }
	});
	$("#mainguid_quality").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#e5732f');
	    	 },
	    mouseout:function(){
	    	    $(this).css('background-color','#ff8034');
	    	 }
	});
	$("#mainguid_portoffice").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#5667e5');
	    	 },
	    mouseout:function(){
	    	    $(this).css('background-color','#6073ff');
	    	 }
	});
	$("#mainguid_sea").bind({
	    mouseover:function(){
	    		 $(this).css('background-color','#123f99');
	    	 },
	    mouseout:function(){
	    	    $(this).css('background-color','#1446aa');
	    	 }
	});
	
	
}