package com.zjport.util;

import java.io.Serializable;
import java.util.List;



/**
 * 报表图表信息表
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
public class ChartData implements Serializable {

    private String name;

    private List<Double> value;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Double> getValue() {
        return value;
    }

    public void setValue(List<Double> value) {
        this.value = value;
    }







}