
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SynchUser", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://101.68.92.118:88/services/SynchUser.asmx?wsdl")
public class SynchUser
    extends Service
{

    private final static URL SYNCHUSER_WSDL_LOCATION;
    private final static WebServiceException SYNCHUSER_EXCEPTION;
    private final static QName SYNCHUSER_QNAME = new QName("http://tempuri.org/", "SynchUser");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://101.68.92.118:88/services/SynchUser.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYNCHUSER_WSDL_LOCATION = url;
        SYNCHUSER_EXCEPTION = e;
    }

    public SynchUser() {
        super(__getWsdlLocation(), SYNCHUSER_QNAME);
    }

    public SynchUser(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYNCHUSER_QNAME, features);
    }

    public SynchUser(URL wsdlLocation) {
        super(wsdlLocation, SYNCHUSER_QNAME);
    }

    public SynchUser(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYNCHUSER_QNAME, features);
    }

    public SynchUser(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SynchUser(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SynchUserSoap
     */
    @WebEndpoint(name = "SynchUserSoap")
    public SynchUserSoap getSynchUserSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SynchUserSoap"), SynchUserSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynchUserSoap
     */
    @WebEndpoint(name = "SynchUserSoap")
    public SynchUserSoap getSynchUserSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SynchUserSoap"), SynchUserSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SynchUserSoap
     */
    @WebEndpoint(name = "SynchUserSoap12")
    public SynchUserSoap getSynchUserSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "SynchUserSoap12"), SynchUserSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynchUserSoap
     */
    @WebEndpoint(name = "SynchUserSoap12")
    public SynchUserSoap getSynchUserSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SynchUserSoap12"), SynchUserSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYNCHUSER_EXCEPTION!= null) {
            throw SYNCHUSER_EXCEPTION;
        }
        return SYNCHUSER_WSDL_LOCATION;
    }

}
