
package com.zjport.smart.ThirdInfoService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ThirdInfoServicePortType", targetNamespace = "http://webservice.cms.hikvision.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ThirdInfoServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getCameraInfoByDeviceInfo")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getCameraInfoByDeviceInfo", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetCameraInfoByDeviceInfo")
    @ResponseWrapper(localName = "getCameraInfoByDeviceInfoResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetCameraInfoByDeviceInfoResponse")
    public String getCameraInfoByDeviceInfo(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:userLogout")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "userLogout", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.UserLogout")
    @ResponseWrapper(localName = "userLogoutResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.UserLogoutResponse")
    public String userLogout(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getDeviceStatus")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getDeviceStatus", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetDeviceStatus")
    @ResponseWrapper(localName = "getDeviceStatusResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetDeviceStatusResponse")
    public String getDeviceStatus(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllControlCenterForList")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getAllControlCenterForList", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllControlCenterForList")
    @ResponseWrapper(localName = "getAllControlCenterForListResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllControlCenterForListResponse")
    public String getAllControlCenterForList(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:userLogin")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "userLogin", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.UserLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.UserLoginResponse")
    public String userLogin(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getPreviewParam")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getPreviewParam", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetPreviewParam")
    @ResponseWrapper(localName = "getPreviewParamResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetPreviewParamResponse")
    public String getPreviewParam(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getPlaybackParam")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getPlaybackParam", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetPlaybackParam")
    @ResponseWrapper(localName = "getPlaybackParamResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetPlaybackParamResponse")
    public String getPlaybackParam(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllRegionInfoForList")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getAllRegionInfoForList", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllRegionInfoForList")
    @ResponseWrapper(localName = "getAllRegionInfoForListResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllRegionInfoForListResponse")
    public String getAllRegionInfoForList(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllDevice")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getAllDevice", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllDevice")
    @ResponseWrapper(localName = "getAllDeviceResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllDeviceResponse")
    public String getAllDevice(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllCamera")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getAllCamera", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllCamera")
    @ResponseWrapper(localName = "getAllCameraResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetAllCameraResponse")
    public String getAllCamera(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:userOnlineHeartbeat")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "userOnlineHeartbeat", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.UserOnlineHeartbeat")
    @ResponseWrapper(localName = "userOnlineHeartbeatResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.UserOnlineHeartbeatResponse")
    public String userOnlineHeartbeat(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getCameraStatus")
    @WebResult(targetNamespace = "http://webservice.cms.hikvision.com")
    @RequestWrapper(localName = "getCameraStatus", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetCameraStatus")
    @ResponseWrapper(localName = "getCameraStatusResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "com.visionagent.client.GetCameraStatusResponse")
    public String getCameraStatus(
            @WebParam(name = "request", targetNamespace = "http://webservice.cms.hikvision.com")
            String request);

}
