
package com.zjport.smart.ThirdInfoService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ThirdInfoService", targetNamespace = "http://webservice.cms.hikvision.com", wsdlLocation = "http://10.100.70.202:8011/services/ThirdInfoService?wsdl")
public class ThirdInfoService
    extends Service
{

    private final static URL THIRDINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException THIRDINFOSERVICE_EXCEPTION;
    private final static QName THIRDINFOSERVICE_QNAME = new QName("http://webservice.cms.hikvision.com", "ThirdInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.70.202:8011/services/ThirdInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        THIRDINFOSERVICE_WSDL_LOCATION = url;
        THIRDINFOSERVICE_EXCEPTION = e;
    }

    public ThirdInfoService() {
        super(__getWsdlLocation(), THIRDINFOSERVICE_QNAME);
    }

    public ThirdInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), THIRDINFOSERVICE_QNAME, features);
    }

    public ThirdInfoService(URL wsdlLocation) {
        super(wsdlLocation, THIRDINFOSERVICE_QNAME);
    }

    public ThirdInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, THIRDINFOSERVICE_QNAME, features);
    }

    public ThirdInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ThirdInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ThirdInfoServicePortType
     */
    @WebEndpoint(name = "ThirdInfoServiceHttpSoap11Endpoint")
    public ThirdInfoServicePortType getThirdInfoServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://webservice.cms.hikvision.com", "ThirdInfoServiceHttpSoap11Endpoint"), ThirdInfoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThirdInfoServicePortType
     */
    @WebEndpoint(name = "ThirdInfoServiceHttpSoap11Endpoint")
    public ThirdInfoServicePortType getThirdInfoServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.cms.hikvision.com", "ThirdInfoServiceHttpSoap11Endpoint"), ThirdInfoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (THIRDINFOSERVICE_EXCEPTION!= null) {
            throw THIRDINFOSERVICE_EXCEPTION;
        }
        return THIRDINFOSERVICE_WSDL_LOCATION;
    }

}
